In [1]:
import pandas as pd
DATA_DIR = r"C:\Users\HARDPC\Desktop\AL\projekty\products_prices_historical_analysis\keepa_data"

In [2]:
meta = pd.read_csv(DATA_DIR + r"\all_products_meta.csv")

meta.shape
meta.info()

KEEPA_EPOCH = pd.Timestamp("2011-01-01")
meta['listed_since'] = KEEPA_EPOCH + pd.to_timedelta(meta['listedSince'], unit = 'min')
meta['tracking_since'] = KEEPA_EPOCH + pd.to_timedelta(meta['trackingSince'], unit = 'min')

meta["tracking_gap_days"] = (meta["tracking_since"] - meta["listed_since"]).dt.days
meta[["asin", "brand", "model", "listed_since", "tracking_since", "tracking_gap_days"]].sort_values("tracking_gap_days", ascending=False)

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   asin           19 non-null     str
 1   title          19 non-null     str
 2   brand          19 non-null     str
 3   model          19 non-null     str
 4   manufacturer   19 non-null     str
 5   productGroup   19 non-null     str
 6   binding        13 non-null     str
 7   color          19 non-null     str
 8   size           19 non-null     str
 9   monthlySold    19 non-null     int64
 10  listedSince    19 non-null     int64
 11  trackingSince  19 non-null     int64
 12  rootCategory   19 non-null     int64
 13  parentAsin     17 non-null     str
dtypes: int64(4), str(10)
memory usage: 2.2 KB

,asin,brand,model,listed_since,tracking_since,tracking_gap_days
14,B09VH9BKHS,Samsung,Galaxy S22+,2022-03-14 14:02:00,2022-06-23 21:06:00,101
2,B09LNW3CY2,Apple,iPhone 13,2021-11-11 19:56:00,2022-01-13 20:40:00,63
1,B08PP5MSVB,Apple,iPhone 12,2020-12-03 22:00:00,2021-02-04 22:16:00,63
9,B0FRKS39NK,Apple,iPhone 17,2025-10-07 07:00:00,2025-11-04 07:44:00,28
15,B0BL8HPF13,Google,Pixel 7,2022-11-02 20:04:00,2022-11-29 22:34:00,27
5,B0CMPMY9ZZ,Apple,iPhone 15,2023-11-05 23:28:00,2023-11-21 06:40:00,15
3,B0BN72FYFG,Apple,iPhone 14,2022-11-23 23:02:00,2022-12-09 19:24:00,15
13,B09SYSMCX6,Google,Pixel 6,2022-02-21 04:08:00,2022-03-07 23:52:00,14
0,B07ZPKN6YR,Apple,iPhone 11,2019-10-28 07:00:00,2019-11-08 20:20:00,11
4,B0C5S83319,Samsung,Galaxy S23,2023-05-19 21:02:00,2023-05-30 18:10:00,10
6,B0D364RMMP,Samsung,Galaxy S24,2024-05-02 17:02:00,2024-05-08 00:12:00,5
12,B08VLMQ3KS,Samsung,Galaxy S21,2021-02-01 22:38:00,2021-02-07 20:40:00,5
11,B08MV7HWFK,Google,Pixel 5,2020-11-05 07:54:00,2020-11-06 18:18:00,1
7,B0DHJDPYYR,Apple,iPhone 16,2024-10-20 07:00:00,2024-10-22 03:48:00,1
10,B08L34JQ9C,Samsung,Galaxy S20 FE,2020-10-12 02:42:00,2020-10-13 07:06:00,1
16,B0CVYKL34H,Google,Pixel 8,2024-02-19 17:28:00,2024-02-21 05:50:00,1
18,B0FFTV1LXZ,Google,Pixel 10,2025-08-20 16:00:00,2025-07-30 19:36:00,-21
8,B0FG1THCD7,Samsung,Galaxy S25 FE,2025-09-04 09:30:00,2025-07-24 23:44:00,-42
17,B0DVHV7X53,Google,Pixel 9a,2025-04-10 04:00:00,2025-02-14 17:56:00,-55

In [3]:
meta.info()
KEEPA_EPOCH = pd.Timestamp("2011-01-01")
meta['listed_since'] = KEEPA_EPOCH + pd.to_timedelta(meta['listedSince'], unit = 'min')
meta['tracking_since'] = KEEPA_EPOCH + pd.to_timedelta(meta['trackingSince'], unit = 'min')
meta["tracking_gap_days"] = (meta["tracking_since"] - meta["listed_since"]).dt.days
meta[["asin", "brand", "model", "listed_since", "tracking_since", "tracking_gap_days"]].sort_values("tracking_gap_days", ascending=False)

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   asin               19 non-null     str
 1   title              19 non-null     str
 2   brand              19 non-null     str
 3   model              19 non-null     str
 4   manufacturer       19 non-null     str
 5   productGroup       19 non-null     str
 6   binding            13 non-null     str
 7   color              19 non-null     str
 8   size               19 non-null     str
 9   monthlySold        19 non-null     int64
 10  listedSince        19 non-null     int64
 11  trackingSince      19 non-null     int64
 12  rootCategory       19 non-null     int64
 13  parentAsin         17 non-null     str
 14  listed_since       19 non-null     datetime64[us]
 15  tracking_since     19 non-null     datetime64[us]
 16  tracking_gap_days  19 non-null     int64
dtypes: datetime64[us](2), int64(5), str(10)
memory usage: 2.7 KB

,asin,brand,model,listed_since,tracking_since,tracking_gap_days
14,B09VH9BKHS,Samsung,Galaxy S22+,2022-03-14 14:02:00,2022-06-23 21:06:00,101
2,B09LNW3CY2,Apple,iPhone 13,2021-11-11 19:56:00,2022-01-13 20:40:00,63
1,B08PP5MSVB,Apple,iPhone 12,2020-12-03 22:00:00,2021-02-04 22:16:00,63
9,B0FRKS39NK,Apple,iPhone 17,2025-10-07 07:00:00,2025-11-04 07:44:00,28
15,B0BL8HPF13,Google,Pixel 7,2022-11-02 20:04:00,2022-11-29 22:34:00,27
5,B0CMPMY9ZZ,Apple,iPhone 15,2023-11-05 23:28:00,2023-11-21 06:40:00,15
3,B0BN72FYFG,Apple,iPhone 14,2022-11-23 23:02:00,2022-12-09 19:24:00,15
13,B09SYSMCX6,Google,Pixel 6,2022-02-21 04:08:00,2022-03-07 23:52:00,14
0,B07ZPKN6YR,Apple,iPhone 11,2019-10-28 07:00:00,2019-11-08 20:20:00,11
4,B0C5S83319,Samsung,Galaxy S23,2023-05-19 21:02:00,2023-05-30 18:10:00,10
6,B0D364RMMP,Samsung,Galaxy S24,2024-05-02 17:02:00,2024-05-08 00:12:00,5
12,B08VLMQ3KS,Samsung,Galaxy S21,2021-02-01 22:38:00,2021-02-07 20:40:00,5
11,B08MV7HWFK,Google,Pixel 5,2020-11-05 07:54:00,2020-11-06 18:18:00,1
7,B0DHJDPYYR,Apple,iPhone 16,2024-10-20 07:00:00,2024-10-22 03:48:00,1
10,B08L34JQ9C,Samsung,Galaxy S20 FE,2020-10-12 02:42:00,2020-10-13 07:06:00,1
16,B0CVYKL34H,Google,Pixel 8,2024-02-19 17:28:00,2024-02-21 05:50:00,1
18,B0FFTV1LXZ,Google,Pixel 10,2025-08-20 16:00:00,2025-07-30 19:36:00,-21
8,B0FG1THCD7,Samsung,Galaxy S25 FE,2025-09-04 09:30:00,2025-07-24 23:44:00,-42
17,B0DVHV7X53,Google,Pixel 9a,2025-04-10 04:00:00,2025-02-14 17:56:00,-55

In [7]:
ph = pd.read_csv(DATA_DIR + r"\B09LNW3CY2_price_history.csv")
ph.shape
ph.head(10)
ph.info


price_cols = ["AMAZON", "NEW", "USED", "LISTPRICE", "REFURBISHED"]
ph[price_cols].notna().sum()

AMAZON         3233
NEW            6483
USED           3367
LISTPRICE        54
REFURBISHED    1274
dtype: int64

In [8]:
#price history data loading - combining all price history .csv files into one DF - os + pandas
#note - data/ files are not shared in repo, as it would obviously be very ineffective, samples in data_schema_examples.md
import os
import pandas as pd

df = pd.DataFrame()
df2 = pd.DataFrame()
data_path = os.path.join('../data/')
for file in os.listdir(data_path):
    if '_price_history' in file:
        df2 = pd.read_csv(data_path + file)
        df = pd.concat([df, df2])

In [9]:
#data resampling - from the loaded 
filtered_df = df[df['NEW'].notna()]
filtered_df['datetime'] = pd.to_datetime(filtered_df['datetime'])
filtered_df = filtered_df.set_index('datetime', drop = True)

pre_filtered_df = filtered_df.groupby("asin").resample("W")["NEW"].min()
print(pre_filtered_df)
filtered_df = filtered_df.groupby("asin").resample("W")["NEW"].min().reset_index()
print(filtered_df)
print(filtered_df['NEW'].notna().sum()) #There are still 78 NaN values (out of 3062 values, 2.5% - it's alright), which means in case of 78 weeks in total we have no price points.
#I thought about using a mean of previous/next row, but we can also assume that the price DID NOT CHANGE during that time, so using ffill makes more sense here.

filtered_df['NEW'] = filtered_df.groupby('asin')['NEW'].ffill()
print(filtered_df['NEW'].notna().sum())
print(filtered_df.columns)
print(filtered_df.head())

asin        datetime
B07ZPKN6YR  2019-11-10    649.99
            2019-11-17    649.99
            2019-11-24    649.99
            2019-12-01    659.99
            2019-12-08    659.99
                           ...
B0FRKS39NK  2026-02-15    827.99
            2026-02-22    761.02
            2026-03-01    730.14
            2026-03-08    782.99
            2026-03-15    771.82
Name: NEW, Length: 3062, dtype: float64
            asin   datetime     NEW
0     B07ZPKN6YR 2019-11-10  649.99
1     B07ZPKN6YR 2019-11-17  649.99
2     B07ZPKN6YR 2019-11-24  649.99
3     B07ZPKN6YR 2019-12-01  659.99
4     B07ZPKN6YR 2019-12-08  659.99
...          ...        ...     ...
3057  B0FRKS39NK 2026-02-15  827.99
3058  B0FRKS39NK 2026-02-22  761.02
3059  B0FRKS39NK 2026-03-01  730.14
3060  B0FRKS39NK 2026-03-08  782.99
3061  B0FRKS39NK 2026-03-15  771.82

[3062 rows x 3 columns]
2984
3062
Index(['asin', 'datetime', 'NEW'], dtype='str')
         asin   datetime     NEW
0  B07ZPKN6YR 2019-11-10  649.99
1  B07ZPKN6YR 2019-11-17  649.99
2  B07ZPKN6YR 2019-11-24  649.99
3  B07ZPKN6YR 2019-12-01  659.99
4  B07ZPKN6YR 2019-12-08  659.99

In [ ]:
#W1 D3 - rows where USED is not null + convert datetime + set datetime
#T1
# combined_df = df[df['USED'].notna()]
# combined_df['datetime'] = pd.to_datetime(combined_df['datetime'])
# print(combined_df.shape)
# combined_df.head(3)
# combined_df = combined_df.set_index('datetime', drop = True)

# #T2
# resampled_df = combined_df.groupby('asin').resample('W').min().reset_index() #resmapling to get the min price for each asin for each week
# print(resampled_df['USED'].isna().sum()) #168 nulls at this point
# resampled_df['USED'] = resampled_df['USED'].ffill()
# print(resampled_df['USED'].isna().sum()) #0 nulls at this point
# print(resampled_df.head(5))
# print(resampled_df['asin'].value_counts())


#T4
meta_path = '../data/all_products_meta.csv'
meta = pd.read_csv(meta_path)
meta['listed_since'] = KEEPA_EPOCH + pd.to_timedelta(meta['listedSince'], 'minutes')
meta = meta[['asin', 'brand', 'model', 'listed_since']]

#T5 - merged meta with resampled minimum NEW prices on weekly interval
merged_df = filtered_df.merge(meta, on = 'asin') #merged meta with resampled NEW prices
print(merged_df.shape)
print(merged_df.dtypes)
print(merged_df.head())

#T6 - filtered for iphone 13 only (asin = B09LNW3CY2)
iphone13_df = merged_df[merged_df['asin'] == 'B09LNW3CY2']
print(iphone13_df)

#T7 - simple line chart - I needed to check the Plotly docs for this, as we haven't learned it before, but it was easy tbh.
import plotly.express as px
chart = px.line(iphone13_df, x='datetime', y='NEW', title = 'iPhone 13 price over time')
chart.show()

(3062, 6)
asin                       str
datetime        datetime64[us]
NEW                    float64
brand                      str
model                      str
listed_since    datetime64[us]
dtype: object
         asin   datetime     NEW  brand      model        listed_since
0  B07ZPKN6YR 2019-11-10  649.99  Apple  iPhone 11 2019-10-28 07:00:00
1  B07ZPKN6YR 2019-11-17  649.99  Apple  iPhone 11 2019-10-28 07:00:00
2  B07ZPKN6YR 2019-11-24  649.99  Apple  iPhone 11 2019-10-28 07:00:00
3  B07ZPKN6YR 2019-12-01  659.99  Apple  iPhone 11 2019-10-28 07:00:00
4  B07ZPKN6YR 2019-12-08  659.99  Apple  iPhone 11 2019-10-28 07:00:00
            asin   datetime     NEW  brand      model        listed_since
1429  B09LNW3CY2 2022-01-16  729.99  Apple  iPhone 13 2021-11-11 19:56:00
1430  B09LNW3CY2 2022-01-23  729.99  Apple  iPhone 13 2021-11-11 19:56:00
1431  B09LNW3CY2 2022-01-30  729.99  Apple  iPhone 13 2021-11-11 19:56:00
1432  B09LNW3CY2 2022-02-06  729.99  Apple  iPhone 13 2021-11-11 19:56:00
1433  B09LNW3CY2 2022-02-13  729.99  Apple  iPhone 13 2021-11-11 19:56:00
...          ...        ...     ...    ...        ...                 ...
1642  B09LNW3CY2 2026-02-15  256.00  Apple  iPhone 13 2021-11-11 19:56:00
1643  B09LNW3CY2 2026-02-22  253.00  Apple  iPhone 13 2021-11-11 19:56:00
1644  B09LNW3CY2 2026-03-01  253.00  Apple  iPhone 13 2021-11-11 19:56:00
1645  B09LNW3CY2 2026-03-08  249.00  Apple  iPhone 13 2021-11-11 19:56:00
1646  B09LNW3CY2 2026-03-15  248.90  Apple  iPhone 13 2021-11-11 19:56:00

[218 rows x 6 columns]